// <auto-generated />
using EntityFrameworkCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFrameworkCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260830064725_DataSeedCurrencyTable")]
    partial class DataSeedCurrencyTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityFrameworkCore.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedOn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("isActive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = "30-08-2026 12:17:24",
                            Description = "Description for Harry Potter 1",
                            Title = "Harry Potter 1",
                            isActive = "true"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = "30-08-2026 12:17:24",
                            Description = "Description for Harry Potter 2",
                            Title = "Harry Potter 2",
                            isActive = "true"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = "30-08-2026 12:17:24",
                            Description = "Description for Harry Potter 3",
                            Title = "Harry Potter 3",
                            isActive = "true"
                        });
                });

            modelBuilder.Entity("EntityFrameworkCore.Models.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Rupee"
                        },
                        new
                        {
                            Id = 2,
                            Title = "USD"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Dinar"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
